[project]
name = "fake-arcpy"
version = "0.0.1"
authors = [
  { name="Travis Bock", email="tbock@innovateteam.com" },
]
description = "A package for faking arcpy during testing in environments where arcpy is unavailable."
requires-python = ">=3.11"
